SHH js files and scripts in the index.html
kennguyen0303/SOEN343_Delivery-3- pull request #10
Opened 2020-11-30 02:44 UTC by Alex-DSJ

classes for SHH system in a new js file called "SHH_functions.js"
add some script to the index file.

2020-11-30 03:25 UTC, kennguyen0303 commented on src/main/resources/static/SHH_functions.js
> +class Room{
Class room already exists

2020-11-30 03:26 UTC, kennguyen0303 commented on src/main/resources/static/SHH_functions.js
> +class Room{
please check Classes.js to modify the class; unless u want to change your class name to avoid duplication with the one in Classes.js

2020-11-30 03:27 UTC, kennguyen0303 commented on src/main/resources/static/index.html
There is no more script in the index.html

2020-11-30 03:30 UTC, kennguyen0303 requested changes
Please update your code based on "refactoring" branch (Or, main branch, I just merged it to avoid further error).

Some note: 

1. Class Room exists in the Classes.js; 
2. No script in the index.html

2020-12-02 22:19 UTC, Alex-DSJ commented
wrong pull request

2020-12-02 22:19 UTC, closed without merging